version: 2.0
jobs:
        build:
                docker:
                        - image: drempost/lamp:latest
                
                steps:
                        - checkout

                        - run:
                                name: run apache2
                                command: service apache2 start
                                command: service mysql start
