version: 2.0
jobs:
        build:
                docker:
                        - image: drempost/lamp:latest
                
                steps:
                        - checkout

                        - run:
                                name: run apache2
                                command: |
                                        service apache2 start
                                        service mysql start
                        - run:
                                name: Setup AWS credentials
                                command: |
                                        mkdir ~/.aws && printf "[profile eb-cli]\naws_access_key_id = ${AWS_ACCESS_KEY_ID}\naws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" > ~/.aws/config
                        - deploy:
                                name: Deploy to Elastic Beanstalk
                                command: |
                                        eb deploy environment-name
