version: 2.0
jobs:
        build:
                docker:
                        - image: drempost/lamp:latest
                
                steps:
                        - checkout

                        - run:
                                name: run container
                                command: service apache2 start                
